export const REPRESENTATION_OPTIONS = [
  { id: "black", label: "Black / African diaspora" },
  { id: "east-asian", label: "East Asian" },
  { id: "south-asian", label: "South Asian" },
  { id: "southeast-asian", label: "Southeast Asian" },
  { id: "middle-eastern", label: "Middle Eastern / West Asian" },
  { id: "latina", label: "Latina / Latin American" },
  { id: "indigenous", label: "Indigenous" },
  { id: "white", label: "White / European" },
  { id: "multiracial", label: "Multiracial" },
] as const;

export type RepresentationTag = (typeof REPRESENTATION_OPTIONS)[number]["id"];

// These tags are editorial catalog metadata, not traits inferred from photos.
// Multiple tags preserve mixed and overlapping public identities.
export const MUSE_REPRESENTATION_TAGS: Record<string, RepresentationTag[]> = {
  aaliyah: ["black"],
  "adaora-akubilo": ["black"],
  "adriana-lima": ["latina", "multiracial"],
  "aishwarya-rai": ["south-asian"],
  "alessandra-ambrosio": ["latina", "white"],
  "alexina-graham": ["white"],
  "alicia-keys": ["black", "multiracial"],
  "ana-de-armas": ["latina", "white"],
  "angela-bassett": ["black"],
  angelababy: ["east-asian"],
  "angelina-jolie": ["white"],
  "anok-yai": ["black"],
  "ariana-grande": ["white"],
  "audrey-hepburn": ["white"],
  "aya-jones": ["black", "multiracial"],
  "ayaka-miyoshi": ["east-asian"],
  beyonce: ["black"],
  brandy: ["black"],
  "brenda-schad": ["indigenous", "white", "multiracial"],
  "brenda-sykes": ["black"],
  "brigitte-bardot": ["white"],
  "cameron-diaz": ["latina", "white", "multiracial"],
  cassie: ["black", "southeast-asian", "latina", "multiracial"],
  "cate-blanchett": ["white"],
  "chanel-iman": ["black", "east-asian", "multiracial"],
  "charlize-theron": ["white"],
  "deepika-padukone": ["south-asian"],
  "devon-aoki": ["east-asian", "white", "multiracial"],
  "dorothy-dandridge": ["black"],
  "doutzen-kroes": ["white"],
  "duckie-thot": ["black"],
  "eiza-gonzalez": ["latina", "white"],
  "elizabeth-taylor": ["white"],
  "elsa-hosk": ["white"],
  "emma-stone": ["white"],
  "eva-longoria": ["latina"],
  "eva-mendes": ["latina"],
  "gemma-chan": ["east-asian"],
  "gisele-bundchen": ["latina", "white"],
  "grace-kelly": ["white"],
  "gwyneth-paltrow": ["white"],
  "halle-berry": ["black", "white", "multiracial"],
  "heidi-klum": ["white"],
  "izabel-goulart": ["latina", "white"],
  "jasmine-tookes": ["black"],
  "jennifer-aniston": ["white"],
  "jennifer-connelly": ["white"],
  "jennifer-lopez": ["latina"],
  "jessica-alba": ["latina", "white", "multiracial"],
  "jhene-aiko": ["black", "east-asian", "latina", "multiracial"],
  "julia-roberts": ["white"],
  "karlie-kloss": ["white"],
  "karolina-kurkova": ["white"],
  "kate-hudson": ["white"],
  "kate-winslet": ["white"],
  "kendall-jenner": ["white"],
  "kim-kardashian": ["middle-eastern", "white", "multiracial"],
  "kirsten-dunst": ["white"],
  "kristin-kreuk": ["east-asian", "white", "multiracial"],
  "lee-hyori": ["east-asian"],
  "leomie-anderson": ["black"],
  "lily-aldridge": ["white"],
  "lindsey-ellingson": ["white"],
  "lucy-liu": ["east-asian"],
  "lupita-nyong-o": ["black"],
  "margot-robbie": ["white"],
  "marilyn-monroe": ["white"],
  "meagan-good": ["black"],
  "michelle-reis": ["east-asian", "white", "multiracial"],
  "miranda-kerr": ["white"],
  "monica-bellucci": ["white"],
  "monika-jagaciak": ["white"],
  "nadine-nassib-njeim": ["middle-eastern"],
  "nana-komatsu": ["east-asian"],
  "naomi-campbell": ["black"],
  "ni-ni": ["east-asian"],
  "nia-long": ["black"],
  "nicole-kidman": ["white"],
  "penelope-cruz": ["white"],
  "priyanka-chopra": ["south-asian"],
  "reese-witherspoon": ["white"],
  rihanna: ["black"],
  "rosie-huntington-whiteley": ["white"],
  "sabrina-carpenter": ["white"],
  "salma-hayek": ["latina", "middle-eastern", "multiracial"],
  "sandra-bullock": ["white"],
  "scarlett-johansson": ["white"],
  "selita-ebanks": ["black"],
  "shu-qi": ["east-asian"],
  "sofia-vergara": ["latina"],
  "song-hye-kyo": ["east-asian"],
  "sui-he": ["east-asian"],
  "suyane-moreira": ["black", "indigenous", "latina", "multiracial"],
  "sydney-sweeney": ["white"],
  "taylor-hill": ["white"],
  "taylor-russell": ["black", "white", "multiracial"],
  "taylor-swift": ["white"],
  "tyra-banks": ["black"],
  "willow-allen": ["indigenous"],
  "yukie-nakama": ["east-asian"],
  zendaya: ["black", "white", "multiracial"],
  "zhang-ziyi": ["east-asian"],
  "zoe-saldana": ["black", "latina", "multiracial"],
};

export function representationLabel(tag: RepresentationTag) {
  return REPRESENTATION_OPTIONS.find((option) => option.id === tag)?.label || tag;
}
